### ISSUE TITLE
Fix hardcoded submodule checkout

### ISSUE THREAD

**Issue by grzanka** [APTG/dedx_web#108]
It's a checkout for the subodule. We need to complie the version from Piotr's branch, since the functions on master still return const int *. And since submodules only allow for checkout on latest commit on master or a specific commit on tracked branches we have to checkout manually (default is master:latest)

_Originally posted by @Mexolius in https://github.com/APTG/dedx_web/pull/101#discussion_r745949796_

**Comment by Mexolius** [comment]
This one has been done a while ago, i think we missed it
