### ISSUE TITLE
Energy selection in calculator mode

### ISSUE THREAD

**Issue by grzanka** [APTG/dedx_web#148]
By default, the user will type only one energy value (in MeV/nucl) and would expect the UI to print stopping power and CSDA range.

Moreover, the user would like to type couple (usually < 10) energy values and see the table/list with results.

In an extreme case, the user would like to use the "default energy list" to calculate stopping power and CSDA range, only for the purpose to dump them to CSV/ASCII file.

In all cases, there should be an option to save CSV/ASCII file.

**Comment by Mexolius** [comment]
I think we should move "option to save CSV/ASCII file" to a separate issue. Said issue would also involve adding export support to the plot subpage

**Comment by grzanka** [comment]
> I think we should move "option to save CSV/ASCII file" to a separate issue. Said issue would also involve adding export support to the plot subpage

I agree
