### ISSUE TITLE
Wrong comment on `getDataSeries` method

### ISSUE THREAD

**Issue by grzanka** [APTG/dedx_web#156]
array of materials ?

_Originally posted by @grzanka in https://github.com/APTG/dedx_web/pull/134#r773351195_

**Comment by Mexolius** [comment]
Looks like a missclick @grzanka

**Comment by grzanka** [comment]
Yes, it was autogenerated from a comment in PR

Take a look on a comment here:
https://github.com/APTG/dedx_web/pull/134/files#diff-26612320ef0c2e48021ada61a6a892e168cef7487d9dc817282c09788436b067R119

Comment says:
```
* @returns {DataSeries} array of libdedx materials
```

But the function being described is not returning array of materials, but a dataserie with energies and stopping powers.
