### ISSUE TITLE
(JS-0128) Should not have unused variables

### ISSUE THREAD

**Issue by grzanka** [APTG/dedx_web#80]
## Description
Found variables that are declared but not used anywhere.

## Occurrences
There are 6 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/APTG/dedx_web/issue/JS-0128/occurrences/](https://deepsource.io/gh/APTG/dedx_web/issue/JS-0128/occurrences/)

**Comment by Mexolius** [comment]
Most of the detected problems are false positives.

**Comment by grzanka** [comment]
Seems fixed now
