### ISSUE TITLE
Add proper licence (GPLv3) ?

### ISSUE THREAD

**Issue by grzanka** [APTG/dedx_web#82]

**Comment by grzanka** [comment]
Check licence of libdedx first

**Comment by piotrpolec** [comment]
libdEdx uses GPLv3 license
React uses MIT license
Emscripten uses MIT license
Webassembly uses Apache License


Using code licensed under GPLv3 license forces us to use it as our license as well. Both MIT and Apache license are compatible with GPLv3 license, so there are no problems here.
